docs: fix link for mdx parsing
MDX parsing with latest docusaurus fails:

```
Error: MDX compilation failed for file "/Users/jean/src/github.com/valora-inc/docs/submodules/wallet/docs/connecting-dapps.md"
Cause: Unexpected character `/` (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a link in MDX, use `[text](url)`)
Details:
{
  "column": 27,
  "message": "Unexpected character `/` (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a link in MDX, use `[text](url)`)",
  "line": 9,
  "name": "9:27",
  "place": {
    "line": 9,
    "column": 27,
    "offset": 634,
    "_index": 0,
    "_bufferIndex": 26
  },
  "reason": "Unexpected character `/` (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a link in MDX, use `[text](url)`)",
  "ruleId": "unexpected-character",
  "source": "micromark-extension-mdx-jsx",
  "url": "https://github.com/micromark/micromark-extension-mdx-jsx#unexpected-character-at-expected-expect"
}
```